# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_ol,multi_platform_rhv
# reboot = false
# strategy = enable
# complexity = low
# disruption = low


- (xccdf-var var_virt_sandbox_use_all_caps)

- name: Ensure libsemanage-python installed
  package:
    name: libsemanage-python
    state: present

- name: Set SELinux boolean virt_sandbox_use_all_caps accordingly
  seboolean:
    name: virt_sandbox_use_all_caps
    state: "{{ var_virt_sandbox_use_all_caps }}"
    persistent: yes
