name: Cron
on:
  schedule:
  - cron: "0 0 * * *"
jobs:
  build:
    name: cron
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        uses: mstksg/get-package@v1
        with:
                apt-get: make expat libopenscap8 libxml2-utils ninja-build python3-jinja2 python3-yaml xsltproc
      - name: Make
        run: |
          make clean all
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1.5.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: Automated content rebuild
          COMMIT_AUTHOR_EMAIL: isimluk@fedorapeople.org
          COMMIT_AUTHOR_NAME: Github Actions Automation
          PULL_REQUEST_TITLE: 'Automated build of ComplianceAsContent/content rhel8'
          PULL_REQUEST_BODY: |
            Automated content re-build.
          PULL_REQUEST_BRANCH: update-rebuild
          BRANCH_SUFFIX: timestamp
      - name: Check output environment variable
        run: echo "Pull Request Number - $PULL_REQUEST_NUMBER"
